app:
    build: .
    command: sh -c "node build/src/index.js | npx bunyan"
    ports:
     - "8000"
    links:
     - redisAuth:redis_auth
     - redisChat:redis_chat
     - redisUsermeta:redis_usermeta
    environment:
     - "API_SECRET=BE295A7D-C10F-4448-9198-D5AB142E7546"

redisAuth:
    image: redis:alpine

redisChat:
    image: redis:alpine

redisUsermeta:
    image: redis:alpine
